# This is a basic workflow to help you get started with Actions

name: Update Files from URL Every 4 hours

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update sub
      run: |
        TARGET_FILE="sub"
        URL="https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/BLACK_VLESS_RUS.txt"
        START_LINE=7
        
        head -n 10 "$TARGET_FILE" > temp1.txt
        
        curl -s "$URL" | sed -n "${START_LINE},\$p" >> temp1.txt
        
        mv temp1.txt "$TARGET_FILE"

    - name: Update whitelist
      run: |
          TARGET_FILE="whitelist"
          HEAD_LINES=10
          SKIP_LINES=7
      
          head -n "$HEAD_LINES" "$TARGET_FILE" > temp2.txt
      
          URLS="
          https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt
          https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-checked.txt
          https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-SNI-RU-all.txt
          "
      
          for URL in $URLS; do
              curl -s "$URL" | sed -n "${SKIP_LINES},\$p" >> temp2.txt
          done
      
          mv temp2.txt "$TARGET_FILE"

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        git add .

        git diff-index --quiet HEAD || (git commit -m "chore: keep first 10 lines and append fresh data" && git push)
